### ISSUE TITLE
npm package doesn't contain library for typescript

### ISSUE THREAD

**Issue by Atheyon** [ChristopherKiss/vuex-type-safety#1]
index.ts is missing from package when installed with npm as dependency of typescript project.

**Comment by ManuelSch** [comment]
+1, can confirm:

![image](https://user-images.githubusercontent.com/19313382/47617165-c9453000-dac4-11e8-93ea-4f918ae5e744.png)

**Comment by ChristopherKiss** [comment]
@Atheyon @ManuelSch,

Thanks for the report guys, really not sure what happened, but a republish of the package seems to have fixed this.

Seems like this was an npm issue.
