### ISSUE TITLE
Consider exporting StoreBuilderImpl<R>

### ISSUE THREAD

**Issue by MariusVolkhart** [ChristopherKiss/vuex-type-safety#2]
My use case: I have a "factory" that creates the vuex store. Something like: 

```typescript
function create(): Store {
  const storeBuilder = getStoreBuilder<RootState>()
  // Setup modules
  return storeBuilder.vuexStore()
```

I then have a set of tests, and each test asks the factory for a new instance of the store. All tests after the first fail because the value returned by `getStoreBuilder` is a singleton that was configured by a previous test run.

For now I'm working around this by passing a random string to `getStoreBuilder(string)`, but ideally, I'd be able to create a new instance of the builder myself.

**Comment by ChristopherKiss** [comment]
@MariusVolkhart,

Thank you for your contribution, I've released a new version with this change.
